---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-emma
  namespace: {{ .Values.user }}-dev-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator-pods
  namespace: {{ .Values.user }}-dev-istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemesh-operator-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator-pods
  namespace: {{ .Values.user }}-dev-travel-portal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemesh-operator-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator-pods
  namespace: {{ .Values.user }}-dev-travel-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemesh-operator-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emma
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicemesh-operator-pods
  namespace: {{ .Values.user }}-dev-travel-agency
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicemesh-operator-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emma
